### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by davidpesetsky** [ldebritto/alfred-mail-sorter#2]
Sorry for the elementary question, but having installed the workflow in Alfred, how do I get it to work in Mail.app under Ventura?  Where should the two AppleScripts be placed, and what else needs to be done.  I get "Buscando..." but nothing further appears.

(Hoping this can substitute for MsgFiler when Sonoma comes — trying it out under Ventura.)

**Comment by ldebritto** [comment]
I've made a few changes to make it compatible with Sonoma and I guess it still is compatible with Ventura.

Have you installed the required free app [JSON Helper for AppleScript](https://apps.apple.com/br/app/json-helper-for-applescript/id453114608?mt=12)? It's basically a library to deal with the JSON format needed to go.

Installing the workflow itself is easy: just download the `.alfredworkflow` file and double click it. No need to bother with the AppleScripts, they're here just for full code disclosure.
